CUDA_VISIBLE_DEVICES=0 python ./train_q_net.py \
--env ARCLE \
--data_dir /home/jovyan/ldcq_arc/LDCQ_for_SOLAR/data/train.6f8cd79b.10.11.26 \
--checkpoint_dir /home/jovyan/ldcq_arc/LDCQ_for_SOLAR/checkpoints/gpu0_11.26 \
--q_checkpoint_dir /home/jovyan/ldcq_arc/LDCQ_for_SOLAR/q_checkpoints/gpu0_11.26 \
--skill_model_filename gpu0_skill_model_ARCLE_11.26_400_.pth \
--diffusion_model_filename gpu0_skill_model_ARCLE_11.26_400__diffusion_prior_best.pt \
--total_prior_samples 300 \
--num_prior_samples 300 \
--n_epoch 500 \
--diffusion_steps 500 \
--gpu_name gpu0 \
--a_dim 36 \
--z_dim 256 \
--h_dim 512 \
--s_dim 512 \
--batch_size 64 \
--max_grid_size 10 \
--gamma 0.5 \
--horizon 5

