CUDA_VISIBLE_DEVICES=0 python ./train_diffusion.py \
--env ARCLE \
--data_dir /home/jovyan/ldcq_arc/LDCQ_for_SOLAR/data/train.6f8cd79b.10.11.26 \
--checkpoint_dir /home/jovyan/ldcq_arc/LDCQ_for_SOLAR/checkpoints/gpu0_11.26 \
--skill_model_filename gpu0_skill_model_ARCLE_11.26_400_.pth \
--n_epoch 400 \
--save_cycle 10 \
--diffusion_steps 500 \
--gpu_name gpu0 \
--s_dim 512 \
--batch_size 32 \
--max_grid_size 10
