CUDA_VISIBLE_DEVICES=0 python ./train_skills.py \
--env ARCLE \
--solar_dir /home/jovyan/ldcq_arc/ARC_Single/segment/train.6f8cd79b.10.11.26  \
--test_solar_dir /home/jovyan/ldcq_arc/ARC_Single/segment/test.6f8cd79b.10.11.26  \
--checkpoint_dir /home/jovyan/ldcq_arc/LDCQ_for_SOLAR/checkpoints \
--num_epochs 401 \
--start_training_state_decoder_after 402 \
--state_decoder_type mlp \
--test_on True \
--horizon 5 \
--a_dim 36 \
--z_dim 256 \
--h_dim 512 \
--s_dim 512 \
--gpu_name gpu0 \
--train_diffusion_prior 1 \
--conditional_prior 1 \
--normalize_latent 0 \
--diffusion_steps 100 \
--beta 0.1 \
--test_num 1000 \
--test_cycle 10 \
--save_cycle 20 \
--batch_size 128 \
--max_grid_size 10 \
--date 11.26
