wandb_version: 1

diffusion_prior:
  desc: null
  value: gpu0_skill_model_ARCLE_00.00_best
cfg_weight:
  desc: null
  value: 0.0
per_buffer:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727270442.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
