wandb_version: 1

lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
sample_z:
  desc: null
  value: 0
env_name:
  desc: null
  value: ARCLE
filename:
  desc: null
  value: gpu0_diffusion_ARCLE_00.00
net_type:
  desc: null
  value: unet
diffusion_steps:
  desc: null
  value: 100
skill_model_filename:
  desc: null
  value: gpu0_skill_model_ARCLE_00.00_best.pth
normalize_latent:
  desc: null
  value: 1
schedule:
  desc: null
  value: linear
test_split:
  desc: null
  value: 0.05
append_goals:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727267913.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
